name: supercab
description: A new Flutter application.

version: 1.0.0+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  carousel_pro: ^1.0.0
  cloud_firestore: ^2.2.2
  cupertino_icons: ^1.0.0
  firebase_auth: ^1.4.1
  firebase_core: ^1.3.0
  firebase_database: ^7.1.1
  firebase_storage: ^8.1.3
  flag: ^5.0.1
  flutter_login_facebook: ^0.2.1
  get: any
  google_maps_flutter:
  geolocator: ^5.3.2+2
  geocoder: ^0.2.1
  flutter_polyline_points: ^0.2.4
  google_sign_in: ^4.5.6
  image_picker: ^0.8.1+1
  intl: any
  introduction_screen: ^1.0.7
  location: ^4.3.0
  shared_preferences: ^2.0.6
  http: ^0.13.0
  flutter_svg: any
  credit_card_number_validator: ^1.0.4
  flutter_masked_text: ^0.8.0
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  path_provider:
  firebase_messaging: ^10.0.2
  flutter_local_notifications: any
  flutter_share: ^1.0.5
  firebase_dynamic_links: any
  package_info: any
  permission_handler: ^8.1.1
  webview_flutter: any
  http_auth: any
  clipboard: any
  firebase_mlkit_language: ^1.1.3
  mailer: ^3.3.0
  flutter_ticket_widget: ^0.0.1
  screenshot: ^0.3.0
  image_gallery_saver: 1.6.8
  url_launcher:
  rate_my_app: any
  cloud_functions: ^2.0.0
  flutter_stripe: any
  pay: ^1.0.5


dependency_overrides:
  intl: ^0.17.0-nullsafety.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.8.2
  build_runner:  ^1.11.1

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: Pacifico
      fonts:
        - asset: fontss/Pacifico-Regular.ttf

    - family: RobotoCondensed
      fonts:
        - asset: fontss/RobotoCondensed-Regular.ttf
        - asset: fontss/RobotoCondensed-Bold.ttf
          weight: 700

flutter_intl:
  enabled: true