import 'AirportPriceModel.dart';


List<AirportPriceModel> melbournePriceList = [
  AirportPriceModel(locationName: 'Abbotsford', price: 82),
  AirportPriceModel(locationName: 'Airport West', price: 66),
  AirportPriceModel(locationName: 'Albert Park', price: 84),
  AirportPriceModel(locationName: 'Albion', price: 75),
  AirportPriceModel(locationName: 'Alphington', price: 82),
  AirportPriceModel(locationName: 'Altona', price: 90),
  AirportPriceModel(locationName: 'Altona Meadows', price: 92),
  AirportPriceModel(locationName: 'Anglesea', price: 395),
  AirportPriceModel(locationName: 'Ardeer', price: 70),
  AirportPriceModel(locationName: 'Armadale', price: 95),
  AirportPriceModel(locationName: 'Ascot Vale', price: 65),
  AirportPriceModel(locationName: 'Ashburton', price: 105),
  AirportPriceModel(locationName: 'Ashwood', price: 104),
  AirportPriceModel(locationName: 'Aspendale', price: 145),
  AirportPriceModel(locationName: 'Avalon', price: 169),
  AirportPriceModel(locationName: 'Avondale Heights', price: 65),
  AirportPriceModel(locationName: 'Bacchus Marsh', price: 150),
  AirportPriceModel(locationName: 'Balaclava', price: 93),
  AirportPriceModel(locationName: 'Ballan', price: 165),
  AirportPriceModel(locationName: 'Balwyn', price: 93),
  AirportPriceModel(locationName: 'Baronia', price: 140),
  AirportPriceModel(locationName: 'Bayswater', price: 149),
  AirportPriceModel(locationName: 'Beaumaris', price: 125),
  AirportPriceModel(locationName: 'Belgrave', price: 165),
  AirportPriceModel(locationName: 'Bentleigh', price: 115),
  AirportPriceModel(locationName: 'Bentleigh East', price: 115),
  AirportPriceModel(locationName: 'Berwick', price: 169),
  AirportPriceModel(locationName: 'Blackburn', price: 110),
  AirportPriceModel(locationName: 'Blackrock', price: 120),
  AirportPriceModel(locationName: 'Box Hill', price: 110),
  AirportPriceModel(locationName: 'Braybrook', price: 70),
  AirportPriceModel(locationName: 'Brighton', price: 100),
  AirportPriceModel(locationName: 'Broadmeadows', price: 60),
  AirportPriceModel(locationName: 'Brunswick', price: 67),
  AirportPriceModel(locationName: 'Burwood', price: 109),
  AirportPriceModel(locationName: 'Burwood East', price: 113),
  AirportPriceModel(locationName: 'Cairnlea', price: 84),
  AirportPriceModel(locationName: 'Camberwell', price: 105),
  AirportPriceModel(locationName: 'Campbellfield', price: 66),
  AirportPriceModel(locationName: 'Canterbury', price: 105),
  AirportPriceModel(locationName: 'Carlton', price: 70),
  AirportPriceModel(locationName: 'Carnegie', price: 105),
  AirportPriceModel(locationName: 'Caroline Springs', price: 80),
  AirportPriceModel(locationName: 'Carrum Downs', price: 140),
  AirportPriceModel(locationName: 'Caulfield', price: 97),
  AirportPriceModel(locationName: 'Caulfield North', price: 97),
  AirportPriceModel(locationName: 'Caulfield South', price: 102),
  AirportPriceModel(locationName: 'CBD', price: 73),
  AirportPriceModel(locationName: 'Chadstone', price: 114),
  AirportPriceModel(locationName: 'Chelsea', price: 144),
  AirportPriceModel(locationName: 'Cheltenham', price: 120),
  AirportPriceModel(locationName: 'Clarinda', price: 130),
  AirportPriceModel(locationName: 'Clayton', price: 118),
  AirportPriceModel(locationName: 'Clayton South', price: 120),
  AirportPriceModel(locationName: 'Clifton Hill', price: 84),
  AirportPriceModel(locationName: 'Coburg', price: 65),
  AirportPriceModel(locationName: 'Collingwood', price: 84),
  AirportPriceModel(locationName: 'Cragieburn', price: 75),
  AirportPriceModel(locationName: 'Cranbourne', price: 185),
  AirportPriceModel(locationName: 'Croydon', price: 144),
  AirportPriceModel(locationName: 'Dandenong', price: 144),
  AirportPriceModel(locationName: 'Deer Park', price: 75),
  AirportPriceModel(locationName: 'Delahey', price: 80),
  AirportPriceModel(locationName: 'Derrimut', price: 75),
  AirportPriceModel(locationName: 'Diamond Creek', price: 101),
  AirportPriceModel(locationName: 'Diggers Rest', price: 101),
  AirportPriceModel(locationName: 'Dingley Village', price: 120),
  AirportPriceModel(locationName: 'Docklands', price: 75),
  AirportPriceModel(locationName: 'Doncaster', price: 101),
  AirportPriceModel(locationName: 'Doncaster East', price: 105),
  AirportPriceModel(locationName: 'Donvale', price: 119),
  AirportPriceModel(locationName: 'Doreen', price: 93),
  AirportPriceModel(locationName: 'Doveton', price: 145),
  AirportPriceModel(locationName: 'East Melbourne', price: 79),
  AirportPriceModel(locationName: 'Edithvale', price: 140),
  AirportPriceModel(locationName: 'Elsternwick', price: 90),
  AirportPriceModel(locationName: 'Eltham', price: 93),
  AirportPriceModel(locationName: 'Elwood', price: 90),
  AirportPriceModel(locationName: 'Endeavour Hills', price: 150),
  AirportPriceModel(locationName: 'Epping', price: 77),
  AirportPriceModel(locationName: 'Essendon', price: 60),
  AirportPriceModel(locationName: 'Fairfield', price: 77),
  AirportPriceModel(locationName: 'Fawkner', price: 60),
  AirportPriceModel(locationName: 'Ferntree Gully', price: 150),
  AirportPriceModel(locationName: 'Fishermans Bend', price: 75),
  AirportPriceModel(locationName: 'Fitzroy', price: 70),
  AirportPriceModel(locationName: 'Fitzroy North', price: 70),
  AirportPriceModel(locationName: 'Flemington', price: 70),
  AirportPriceModel(locationName: 'Footscray', price: 73),
  AirportPriceModel(locationName: 'Forest Hill', price: 130),
  AirportPriceModel(locationName: 'Frankston', price: 180),
  AirportPriceModel(locationName: 'Gardenvale', price: 93),
  AirportPriceModel(locationName: 'Geelong', price: 195),
  AirportPriceModel(locationName: 'Gembrook', price: 220),
  AirportPriceModel(locationName: 'Gisborne', price: 104),
  AirportPriceModel(locationName: 'Glen Huntly', price: 93),
  AirportPriceModel(locationName: 'Glen Iris', price: 99),
  AirportPriceModel(locationName: 'Glen Waverley', price: 120),
  AirportPriceModel(locationName: 'Glenroy', price: 60),
  AirportPriceModel(locationName: 'Greensborough', price: 83),
  AirportPriceModel(locationName: 'Greenvale', price: 65),
  AirportPriceModel(locationName: 'Hallam', price: 162),
  AirportPriceModel(locationName: 'Hampton', price: 105),
  AirportPriceModel(locationName: 'Harkaway', price: 165),
  AirportPriceModel(locationName: 'Hastings', price: 240),
  AirportPriceModel(locationName: 'Hawthorn', price: 93),
  AirportPriceModel(locationName: 'Healesville', price: 190),
  AirportPriceModel(locationName: 'Heatherton', price: 130),
  AirportPriceModel(locationName: 'Heathmont', price: 130),
  AirportPriceModel(locationName: 'Heidelberg', price: 84),
  AirportPriceModel(locationName: 'Highett', price: 112),
  AirportPriceModel(locationName: 'Hillside', price: 80),
  AirportPriceModel(locationName: 'HMAS Cerberus', price: 220),
  AirportPriceModel(locationName: 'Hoppers Crossing', price: 95),
  AirportPriceModel(locationName: 'Hughesdale', price: 112),
  AirportPriceModel(locationName: 'Huntingdale', price: 108),
  AirportPriceModel(locationName: 'Hurstbridge', price: 103),
  AirportPriceModel(locationName: 'Ivanhoe', price: 75),
  AirportPriceModel(locationName: 'Jacana', price: 65),
  AirportPriceModel(locationName: 'Jan Juc', price: 255),
  AirportPriceModel(locationName: 'Jolimont', price: 79),
  AirportPriceModel(locationName: 'Kangaroo Grounds', price: 120),
  AirportPriceModel(locationName: 'Keilor', price: 70),
  AirportPriceModel(locationName: 'Kensington', price: 65),
  AirportPriceModel(locationName: 'Kew', price: 90),
  AirportPriceModel(locationName: 'Keysborough', price: 155),
  AirportPriceModel(locationName: 'Kilsyth', price: 140),
  AirportPriceModel(locationName: 'King Lake', price: 160),
  AirportPriceModel(locationName: 'Kingsbury', price: 75),
  AirportPriceModel(locationName: 'Kingsville', price: 80),
  AirportPriceModel(locationName: 'Knoxfield', price: 125),
  AirportPriceModel(locationName: 'Kooyong', price: 93),
  AirportPriceModel(locationName: 'Langwarrin', price: 199),
  AirportPriceModel(locationName: 'Lara', price: 155),
  AirportPriceModel(locationName: 'Laverton', price: 80),
  AirportPriceModel(locationName: 'Lilydale', price: 159),
  AirportPriceModel(locationName: 'Litttle River', price: 140),
  AirportPriceModel(locationName: 'Lorne', price: 340),
  AirportPriceModel(locationName: 'Lower Plenty', price: 93),
  AirportPriceModel(locationName: 'Lynbrook', price: 165),
  AirportPriceModel(locationName: 'Lysterfield', price: 138),
  AirportPriceModel(locationName: 'Maidstone', price: 74),
  AirportPriceModel(locationName: 'Malvern', price: 97),
  AirportPriceModel(locationName: 'Malvern East', price: 105),
  AirportPriceModel(locationName: 'Maribyrnong', price: 72),
  AirportPriceModel(locationName: 'Meadow Heights', price: 60),
  AirportPriceModel(locationName: 'Melbourne', price: 73),
  AirportPriceModel(locationName: 'Melbourne Airport', price: 60),
  AirportPriceModel(locationName: 'Melton', price: 110),
  AirportPriceModel(locationName: 'Mentone', price: 120),
  AirportPriceModel(locationName: 'Middle Park', price: 84),
  AirportPriceModel(locationName: 'Mill Park', price: 82),
  AirportPriceModel(locationName: 'Mitcham', price: 115),
  AirportPriceModel(locationName: 'Mont Albert', price: 97),
  AirportPriceModel(locationName: 'Montmorency', price: 85),
  AirportPriceModel(locationName: 'Montrose', price: 140),
  AirportPriceModel(locationName: 'Moonee Ponds', price: 65),
  AirportPriceModel(locationName: 'Moorabbin', price: 110),
  AirportPriceModel(locationName: 'Mordialloc', price: 130),
  AirportPriceModel(locationName: 'Mornington', price: 210),
  AirportPriceModel(locationName: 'Mount Dandenong', price: 145),
  AirportPriceModel(locationName: 'Mount Eliza', price: 205),
  AirportPriceModel(locationName: 'Mount Waverley', price: 112),
  AirportPriceModel(locationName: 'Mulgrave', price: 115),
  AirportPriceModel(locationName: 'Murrumbeena', price: 104),
  AirportPriceModel(locationName: 'Narre Warren', price: 169),
  AirportPriceModel(locationName: 'Narre Warren North', price: 160),
  AirportPriceModel(locationName: 'Newport', price: 84),
  AirportPriceModel(locationName: 'Niddrie', price: 60),
  AirportPriceModel(locationName: 'Noble Park', price: 145),
  AirportPriceModel(locationName: 'North Melbourne', price: 73),
  AirportPriceModel(locationName: 'Notting Hill', price: 118),
  AirportPriceModel(locationName: 'Oakleigh', price: 110),
  AirportPriceModel(locationName: 'Oakleigh South', price: 120),
  AirportPriceModel(locationName: 'Officer', price: 195),
  AirportPriceModel(locationName: 'Olinda', price: 147),
  AirportPriceModel(locationName: 'Ormond', price: 100),
  AirportPriceModel(locationName: 'Pakenham', price: 230),
  AirportPriceModel(locationName: 'Park Orchards', price: 120),
  AirportPriceModel(locationName: 'Parkdale', price: 118),
  AirportPriceModel(locationName: 'Parkville', price: 65),
  AirportPriceModel(locationName: 'Pascoe Vale', price: 60),
  AirportPriceModel(locationName: 'Patterson Lakes', price: 160),
  AirportPriceModel(locationName: 'Plenty', price: 84),
  AirportPriceModel(locationName: 'Plumpton', price: 84),
  AirportPriceModel(locationName: 'Point Cook', price: 95),
  AirportPriceModel(locationName: 'Port Melbourne', price: 79),
  AirportPriceModel(locationName: 'Portsea', price: 230),
  AirportPriceModel(locationName: 'Prahran', price: 88),
  AirportPriceModel(locationName: 'Preston', price: 70),
  AirportPriceModel(locationName: 'Queenscliff', price: 240),
  AirportPriceModel(locationName: 'Red hill', price: 230),
  AirportPriceModel(locationName: 'Research', price: 108),
  AirportPriceModel(locationName: 'Reservoir', price: 70),
  AirportPriceModel(locationName: 'Richmond', price: 88),
  AirportPriceModel(locationName: 'Ringwood', price: 120),
  AirportPriceModel(locationName: 'Ripponlea', price: 88),
  AirportPriceModel(locationName: 'Rockbank', price: 84),
  AirportPriceModel(locationName: 'Rosanna', price: 83),
  AirportPriceModel(locationName: 'Rosebud', price: 280),
  AirportPriceModel(locationName: 'Rowville', price: 145),
  AirportPriceModel(locationName: 'Roxburgh Park', price: 68),
  AirportPriceModel(locationName: 'Sanctuary Lakes', price: 97),
  AirportPriceModel(locationName: 'Sandown Park', price: 125),
  AirportPriceModel(locationName: 'Sandringham', price: 110),
  AirportPriceModel(locationName: 'Sassafaras', price: 166),
  AirportPriceModel(locationName: 'Scoresby', price: 140),
  AirportPriceModel(locationName: 'Seabrook', price: 84),
  AirportPriceModel(locationName: 'Seaford', price: 170),
  AirportPriceModel(locationName: 'Seddon', price: 80),
  AirportPriceModel(locationName: 'Skye', price: 180),
  AirportPriceModel(locationName: 'Somerton', price: 70),
  AirportPriceModel(locationName: 'Somerville', price: 190),
  AirportPriceModel(locationName: 'South Melbourne', price: 84),
  AirportPriceModel(locationName: 'South Morang', price: 88),
  AirportPriceModel(locationName: 'South Wharf', price: 79),
  AirportPriceModel(locationName: 'South Yarra', price: 85),
  AirportPriceModel(locationName: 'Southbank', price: 80),
  AirportPriceModel(locationName: 'Spotswood', price: 80),
  AirportPriceModel(locationName: 'Springvale', price: 120),
  AirportPriceModel(locationName: 'St Albans', price: 70),
  AirportPriceModel(locationName: 'St Kilda', price: 88),
  AirportPriceModel(locationName: 'St Kilda East', price: 88),
  AirportPriceModel(locationName: 'St Kilda Rd', price: 84),
  AirportPriceModel(locationName: 'Strathmore', price: 60),
  AirportPriceModel(locationName: 'Sunbury', price: 70),
  AirportPriceModel(locationName: 'Sunshine', price: 70),
  AirportPriceModel(locationName: 'Surrey Hills', price: 105),
  AirportPriceModel(locationName: 'Sydenham', price: 77),
  AirportPriceModel(locationName: 'Tarneit', price: 97),
  AirportPriceModel(locationName: 'Taylors Hill', price: 75),
  AirportPriceModel(locationName: 'Taylors Lakes', price: 75),
  AirportPriceModel(locationName: 'Templestowe', price: 97),
  AirportPriceModel(locationName: 'The Basin', price: 148),
  AirportPriceModel(locationName: 'Thomastown', price: 70),
  AirportPriceModel(locationName: 'Thornbury', price: 70),
  AirportPriceModel(locationName: 'Toorak', price: 92),
  AirportPriceModel(locationName: 'Torquay', price: 260),
  AirportPriceModel(locationName: 'Truganina', price: 80),
  AirportPriceModel(locationName: 'Tullamarine', price: 55),
  AirportPriceModel(locationName: 'Upwey', price: 160),
  AirportPriceModel(locationName: 'Vermont', price: 118),
  AirportPriceModel(locationName: 'Viewbank', price: 85),
  AirportPriceModel(locationName: 'Wallan', price: 111),
  AirportPriceModel(locationName: 'Wantrina', price: 130),
  AirportPriceModel(locationName: 'Warburton', price: 220),
  AirportPriceModel(locationName: 'Warrandyte', price: 117),
  AirportPriceModel(locationName: 'Warranwood', price: 119),
  AirportPriceModel(locationName: 'Watsonia', price: 83),
  AirportPriceModel(locationName: 'Wattle Glen', price: 110),
  AirportPriceModel(locationName: 'Werribee', price: 100),
  AirportPriceModel(locationName: 'West Melbourne', price: 73),
  AirportPriceModel(locationName: 'Wheelers hill', price: 119),
  AirportPriceModel(locationName: 'Whittlesea', price: 113),
  AirportPriceModel(locationName: 'Williamstown', price: 88),
  AirportPriceModel(locationName: 'Windsor', price: 88),
  AirportPriceModel(locationName: 'Wyndham Vale', price: 105),
  AirportPriceModel(locationName: 'Yallambie', price: 77),
  AirportPriceModel(locationName: 'Yan Yean', price: 110),
  AirportPriceModel(locationName: 'Yarra Glen', price: 149),
  AirportPriceModel(locationName: 'Yarrambat', price: 83),
  AirportPriceModel(locationName: 'Yarraville', price: 79),
  AirportPriceModel(locationName: 'Yerring', price: 138),
  AirportPriceModel(locationName: 'Yuroke', price: 66),
];




List<AirportPriceModel> melbourneAvalonPriceList = [
  AirportPriceModel(locationName: 'Abbotsford', price: 158),
  AirportPriceModel(locationName: 'Airport West', price: 154),
  AirportPriceModel(locationName: 'Albert Park', price: 154),
  AirportPriceModel(locationName: 'Albion', price: 135),
  AirportPriceModel(locationName: 'Alphington', price: 205),
  AirportPriceModel(locationName: 'Altona', price: 125),
  AirportPriceModel(locationName: 'Altona Meadows', price: 125),
  AirportPriceModel(locationName: 'Anglesea', price: 250),
  AirportPriceModel(locationName: 'Ardeer', price: 130),
  AirportPriceModel(locationName: 'Armadale', price: 210),
  AirportPriceModel(locationName: 'Ascot Vale', price: 145),
  AirportPriceModel(locationName: 'Ashburton', price: 215),
  AirportPriceModel(locationName: 'Ashwood', price: 205),
  AirportPriceModel(locationName: 'Aspendale', price: 270),
  AirportPriceModel(locationName: 'Avalon', price: 60),
  AirportPriceModel(locationName: 'Avondale Heights', price: 150),
  AirportPriceModel(locationName: 'Bacchus Marsh', price: 150),
  AirportPriceModel(locationName: 'Balaclava', price: 180),
  AirportPriceModel(locationName: 'Ballan', price: 200),
  AirportPriceModel(locationName: 'Balwyn', price: 195),
  AirportPriceModel(locationName: 'Baronia', price: 260),
  AirportPriceModel(locationName: 'Bayswater', price: 280),
  AirportPriceModel(locationName: 'Beaumaris', price: 260),
  AirportPriceModel(locationName: 'Belgrave', price: 350),
  AirportPriceModel(locationName: 'Bentleigh', price: 244),
  AirportPriceModel(locationName: 'Bentleigh East', price: 244),
  AirportPriceModel(locationName: 'Berwick', price: 330),
  AirportPriceModel(locationName: 'Blackburn', price: 185),
  AirportPriceModel(locationName: 'Blackrock', price: 210),
  AirportPriceModel(locationName: 'Box Hill', price: 240),
  AirportPriceModel(locationName: 'Braybrook', price: 134),
  AirportPriceModel(locationName: 'Brighton', price: 225),
  AirportPriceModel(locationName: 'Broadmeadows', price: 180),
  AirportPriceModel(locationName: 'Brunswick', price: 180),
  AirportPriceModel(locationName: 'Burwood', price: 225),
  AirportPriceModel(locationName: 'Burwood East', price: 225),
  AirportPriceModel(locationName: 'Cairnlea', price: 144),
  AirportPriceModel(locationName: 'Camberwell', price: 235),
  AirportPriceModel(locationName: 'Campbellfield', price: 160),
  AirportPriceModel(locationName: 'Canterbury', price: 230),
  AirportPriceModel(locationName: 'Carlton', price: 177),
  AirportPriceModel(locationName: 'Carnegie', price: 220),
  AirportPriceModel(locationName: 'Caroline Springs', price: 125),
  AirportPriceModel(locationName: 'Carrum Downs', price: 280),
  AirportPriceModel(locationName: 'Caulfield', price: 205),
  AirportPriceModel(locationName: 'Caulfield North', price: 205),
  AirportPriceModel(locationName: 'Caulfield South', price: 210),
  AirportPriceModel(locationName: 'CBD', price: 150),
  AirportPriceModel(locationName: 'Chadstone', price: 210),
  AirportPriceModel(locationName: 'Chelsea', price: 230),
  AirportPriceModel(locationName: 'Cheltenham', price: 160),
  AirportPriceModel(locationName: 'Clarinda', price: 225),
  AirportPriceModel(locationName: 'Clayton', price: 150),
  AirportPriceModel(locationName: 'Clayton South', price: 225),
  AirportPriceModel(locationName: 'Clifton Hill', price: 185),
  AirportPriceModel(locationName: 'Coburg', price: 170),
  AirportPriceModel(locationName: 'Collingwood', price: 160),
  AirportPriceModel(locationName: 'Cragieburn', price: 155),
  AirportPriceModel(locationName: 'Cranbourne', price: 300),
  AirportPriceModel(locationName: 'Croydon', price: 290),
  AirportPriceModel(locationName: 'Dandenong', price: 270),
  AirportPriceModel(locationName: 'Deer Park', price: 134),
  AirportPriceModel(locationName: 'Delahey', price: 134),
  AirportPriceModel(locationName: 'Derrimut', price: 124),
  AirportPriceModel(locationName: 'Diamond Creek', price: 270),
  AirportPriceModel(locationName: 'Diggers Rest', price: 220),
  AirportPriceModel(locationName: 'Dingley Village', price: 280),
  AirportPriceModel(locationName: 'Docklands', price: 160),
  AirportPriceModel(locationName: 'Doncaster', price: 210),
  AirportPriceModel(locationName: 'Doncaster East', price: 220),
  AirportPriceModel(locationName: 'Donvale', price: 210),
  AirportPriceModel(locationName: 'Doreen', price: 190),
  AirportPriceModel(locationName: 'Doveton', price: 280),
  AirportPriceModel(locationName: 'East Melbourne', price: 155),
  AirportPriceModel(locationName: 'Edithvale', price: 200),
  AirportPriceModel(locationName: 'Elsternwick', price: 210),
  AirportPriceModel(locationName: 'Eltham', price: 180),
  AirportPriceModel(locationName: 'Elwood', price: 185),
  AirportPriceModel(locationName: 'Endeavour Hills', price: 240),
  AirportPriceModel(locationName: 'Epping', price: 190),
  AirportPriceModel(locationName: 'Essendon', price: 150),
  AirportPriceModel(locationName: 'Fairfield', price: 140),
  AirportPriceModel(locationName: 'Fawkner', price: 180),
  AirportPriceModel(locationName: 'Ferntree Gully', price: 300),
  AirportPriceModel(locationName: 'Fishermans Bend', price: 140),
  AirportPriceModel(locationName: 'Fitzroy', price: 195),
  AirportPriceModel(locationName: 'Fitzroy North', price: 165),
  AirportPriceModel(locationName: 'Flemington', price: 140),
  AirportPriceModel(locationName: 'Footscray', price: 140),
  AirportPriceModel(locationName: 'Forest Hill', price: 195),
  AirportPriceModel(locationName: 'Frankston', price: 275),
  AirportPriceModel(locationName: 'Gardenvale', price: 140),
  AirportPriceModel(locationName: 'Geelong', price: 150),
  AirportPriceModel(locationName: 'Gembrook', price: 410),
  AirportPriceModel(locationName: 'Gisborne', price: 310),
  AirportPriceModel(locationName: 'Glen Huntly', price: 195),
  AirportPriceModel(locationName: 'Glen Iris', price: 195),
  AirportPriceModel(locationName: 'Glen Waverley', price: 180),
  AirportPriceModel(locationName: 'Glenroy', price: 150),
  AirportPriceModel(locationName: 'Greensborough', price: 210),
  AirportPriceModel(locationName: 'Greenvale', price: 165),
  AirportPriceModel(locationName: 'Hallam', price: 290),
  AirportPriceModel(locationName: 'Hampton', price: 195),
  AirportPriceModel(locationName: 'Harkaway', price: 320),
  AirportPriceModel(locationName: 'Hastings', price: 380),
  AirportPriceModel(locationName: 'Hawthorn', price: 170),
  AirportPriceModel(locationName: 'Healesville', price: 380),
  AirportPriceModel(locationName: 'Heatherton', price: 265),
  AirportPriceModel(locationName: 'Heathmont', price: 245),
  AirportPriceModel(locationName: 'Heidelberg', price: 170),
  AirportPriceModel(locationName: 'Highett', price: 195),
  AirportPriceModel(locationName: 'Hillside', price: 125),
  AirportPriceModel(locationName: 'HMAS Cerberus', price: 360),
  AirportPriceModel(locationName: 'Hoppers Crossing', price: 120),
  AirportPriceModel(locationName: 'Hughesdale', price: 160),
  AirportPriceModel(locationName: 'Huntingdale', price: 165),
  AirportPriceModel(locationName: 'Hurstbridge', price: 300),
  AirportPriceModel(locationName: 'Ivanhoe', price: 150),
  AirportPriceModel(locationName: 'Jacana', price: 155),
  AirportPriceModel(locationName: 'Jan Juc', price: 340),
  AirportPriceModel(locationName: 'Jolimont', price: 150),
  AirportPriceModel(locationName: 'Kangaroo Grounds', price: 290),
  AirportPriceModel(locationName: 'Keilor', price: 160),
  AirportPriceModel(locationName: 'Kensington', price: 140),
  AirportPriceModel(locationName: 'Kew', price: 180),
  AirportPriceModel(locationName: 'Keysborough', price: 280),
  AirportPriceModel(locationName: 'Kilsyth', price: 310),
  AirportPriceModel(locationName: 'King Lake', price: 350),
  AirportPriceModel(locationName: 'Kingsbury', price: 175),
  AirportPriceModel(locationName: 'Kingsville', price: 140),
  AirportPriceModel(locationName: 'Knoxfield', price: 270),
  AirportPriceModel(locationName: 'Kooyong', price: 160),
  AirportPriceModel(locationName: 'Langwarrin', price: 300),
  AirportPriceModel(locationName: 'Lara', price: 175),
  AirportPriceModel(locationName: 'Laverton', price: 120),
  AirportPriceModel(locationName: 'Lilydale', price: 250),
  AirportPriceModel(locationName: 'Litttle River', price: 145),
  AirportPriceModel(locationName: 'Lorne', price: 520),
  AirportPriceModel(locationName: 'Lower Plenty', price: 230),
  AirportPriceModel(locationName: 'Lynbrook', price: 300),
  AirportPriceModel(locationName: 'Lysterfield', price: 190),
  AirportPriceModel(locationName: 'Maidstone', price: 140),
  AirportPriceModel(locationName: 'Malvern', price: 195),
  AirportPriceModel(locationName: 'Malvern East', price: 205),
  AirportPriceModel(locationName: 'Maribyrnong', price: 140),
  AirportPriceModel(locationName: 'Meadow Heights', price: 195),
  AirportPriceModel(locationName: 'Melbourne', price: 140),
  AirportPriceModel(locationName: 'Melbourne Airport', price: 150),
  AirportPriceModel(locationName: 'Melton', price: 180),
  AirportPriceModel(locationName: 'Mentone', price: 220),
  AirportPriceModel(locationName: 'Middle Park', price: 150),
  AirportPriceModel(locationName: 'Mill Park', price: 190),
  AirportPriceModel(locationName: 'Mitcham', price: 245),
  AirportPriceModel(locationName: 'Mont Albert', price: 180),
  AirportPriceModel(locationName: 'Montmorency', price: 210),
  AirportPriceModel(locationName: 'Montrose', price: 230),
  AirportPriceModel(locationName: 'Moonee Ponds', price: 150),
  AirportPriceModel(locationName: 'Moorabbin', price: 195),
  AirportPriceModel(locationName: 'Mordialloc', price: 225),
  AirportPriceModel(locationName: 'Mornington', price: 295),
  AirportPriceModel(locationName: 'Mount Dandenong', price: 320),
  AirportPriceModel(locationName: 'Mount Eliza', price: 300),
  AirportPriceModel(locationName: 'Mount Waverley', price: 225),
  AirportPriceModel(locationName: 'Mulgrave', price: 205),
  AirportPriceModel(locationName: 'Murrumbeena', price: 205),
  AirportPriceModel(locationName: 'Narre Warren', price: 220),
  AirportPriceModel(locationName: 'Narre Warren North', price: 220),
  AirportPriceModel(locationName: 'Newport', price: 140),
  AirportPriceModel(locationName: 'Niddrie', price: 150),
  AirportPriceModel(locationName: 'Noble Park', price: 285),
  AirportPriceModel(locationName: 'North Melbourne', price: 150),
  AirportPriceModel(locationName: 'Notting Hill', price: 165),
  AirportPriceModel(locationName: 'Oakleigh', price: 210),
  AirportPriceModel(locationName: 'Oakleigh South', price: 220),
  AirportPriceModel(locationName: 'Officer', price: 365),
  AirportPriceModel(locationName: 'Olinda', price: 325),
  AirportPriceModel(locationName: 'Ormond', price: 180),
  AirportPriceModel(locationName: 'Pakenham', price: 380),
  AirportPriceModel(locationName: 'Park Orchards', price: 205),
  AirportPriceModel(locationName: 'Parkdale', price: 165),
  AirportPriceModel(locationName: 'Parkville', price: 150),
  AirportPriceModel(locationName: 'Pascoe Vale', price: 150),
  AirportPriceModel(locationName: 'Patterson Lakes', price: 270),
  AirportPriceModel(locationName: 'Plenty', price: 220),
  AirportPriceModel(locationName: 'Plumpton', price: 180),
  AirportPriceModel(locationName: 'Point Cook', price: 120),
  AirportPriceModel(locationName: 'Port Melbourne', price: 140),
  AirportPriceModel(locationName: 'Portsea', price: 300),
  AirportPriceModel(locationName: 'Prahran', price: 180),
  AirportPriceModel(locationName: 'Preston', price: 190),
  AirportPriceModel(locationName: 'Queenscliff', price: 245),
  AirportPriceModel(locationName: 'Red hill', price: 345),
  AirportPriceModel(locationName: 'Research', price: 210),
  AirportPriceModel(locationName: 'Reservoir', price: 180),
  AirportPriceModel(locationName: 'Richmond', price: 170),
  AirportPriceModel(locationName: 'Ringwood', price: 200),
  AirportPriceModel(locationName: 'Ripponlea', price: 175),
  AirportPriceModel(locationName: 'Rockbank', price: 120),
  AirportPriceModel(locationName: 'Rosanna', price: 195),
  AirportPriceModel(locationName: 'Rosebud', price: 380),
  AirportPriceModel(locationName: 'Rowville', price: 270),
  AirportPriceModel(locationName: 'Roxburgh Park', price: 155),
  AirportPriceModel(locationName: 'Sanctuary Lakes', price: 120),
  AirportPriceModel(locationName: 'Sandown Park', price: 170),
  AirportPriceModel(locationName: 'Sandringham', price: 195),
  AirportPriceModel(locationName: 'Sassafaras', price: 330),
  AirportPriceModel(locationName: 'Scoresby', price: 270),
  AirportPriceModel(locationName: 'Seabrook', price: 140),
  AirportPriceModel(locationName: 'Seaford', price: 270),
  AirportPriceModel(locationName: 'Seddon', price: 135),
  AirportPriceModel(locationName: 'Skye', price: 295),
  AirportPriceModel(locationName: 'Somerton', price: 180),
  AirportPriceModel(locationName: 'Somerville', price: 260),
  AirportPriceModel(locationName: 'South Melbourne', price: 140),
  AirportPriceModel(locationName: 'South Morang', price: 250),
  AirportPriceModel(locationName: 'South Wharf', price: 140),
  AirportPriceModel(locationName: 'South Yarra', price: 180),
  AirportPriceModel(locationName: 'Southbank', price: 140),
  AirportPriceModel(locationName: 'Spotswood', price: 140),
  AirportPriceModel(locationName: 'Springvale', price: 270),
  AirportPriceModel(locationName: 'St Albans', price: 140),
  AirportPriceModel(locationName: 'St Kilda', price: 205),
  AirportPriceModel(locationName: 'St Kilda East', price: 210),
  AirportPriceModel(locationName: 'St Kilda Rd', price: 150),
  AirportPriceModel(locationName: 'Strathmore', price: 150),
  AirportPriceModel(locationName: 'Sunbury', price: 160),
  AirportPriceModel(locationName: 'Sunshine', price: 140),
  AirportPriceModel(locationName: 'Surrey Hills', price: 205),
  AirportPriceModel(locationName: 'Sydenham', price: 150),
  AirportPriceModel(locationName: 'Tarneit', price: 120),
  AirportPriceModel(locationName: 'Taylors Hill', price: 120),
  AirportPriceModel(locationName: 'Taylors Lakes', price: 120),
  AirportPriceModel(locationName: 'Templestowe', price: 180),
  AirportPriceModel(locationName: 'The Basin', price: 300),
  AirportPriceModel(locationName: 'Thomastown', price: 185),
  AirportPriceModel(locationName: 'Thornbury', price: 165),
  AirportPriceModel(locationName: 'Toorak', price: 205),
  AirportPriceModel(locationName: 'Torquay', price: 325),
  AirportPriceModel(locationName: 'Truganina', price: 120),
  AirportPriceModel(locationName: 'Tullamarine', price: 160),
  AirportPriceModel(locationName: 'Upwey', price: 310),
  AirportPriceModel(locationName: 'Vermont', price: 190),
  AirportPriceModel(locationName: 'Viewbank', price: 180),
  AirportPriceModel(locationName: 'Wallan', price: 360),
  AirportPriceModel(locationName: 'Wantrina', price: 200),
  AirportPriceModel(locationName: 'Warburton', price: 490),
  AirportPriceModel(locationName: 'Warrandyte', price: 250),
  AirportPriceModel(locationName: 'Warranwood', price: 280),
  AirportPriceModel(locationName: 'Watsonia', price: 185),
  AirportPriceModel(locationName: 'Wattle Glen', price: 280),
  AirportPriceModel(locationName: 'Werribee', price: 120),
  AirportPriceModel(locationName: 'West Melbourne', price: 140),
  AirportPriceModel(locationName: 'Wheelers hill', price: 170),
  AirportPriceModel(locationName: 'Whittlesea', price: 320),
  AirportPriceModel(locationName: 'Williamstown', price: 130),
  AirportPriceModel(locationName: 'Windsor', price: 180),
  AirportPriceModel(locationName: 'Wyndham Vale', price: 120),
  AirportPriceModel(locationName: 'Yallambie', price: 190),
  AirportPriceModel(locationName: 'Yan Yean', price: 310),
  AirportPriceModel(locationName: 'Yarra Glen', price: 360),
  AirportPriceModel(locationName: 'Yarrambat', price: 205),
  AirportPriceModel(locationName: 'Yarraville', price: 135),
  AirportPriceModel(locationName: 'Yerring', price: 350),
  AirportPriceModel(locationName: 'Yuroke', price: 210),
];






